# Generated by Django 5.1.4 on 2025-01-24 09:17

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(max_length=200, null=True)),
                ('CategoryImage', models.ImageField(upload_to='CategoryImages/')),
                ('CategoryDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=200, null=True)),
                ('Contactname', models.CharField(max_length=200, null=True)),
                ('ContactTitle', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=200, null=True)),
                ('ClientDescription', ckeditor.fields.RichTextField(null=True)),
                ('ClientPosition', models.CharField(max_length=200, null=True)),
                ('ClientImage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='tblReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewerName', models.CharField(max_length=200, null=True)),
                ('ReviewDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('ReviewDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMediaName', models.CharField(max_length=200, null=True)),
                ('SocialMediaURL', models.CharField(max_length=200, null=True)),
                ('SocialMediaImage', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopMenuName', models.CharField(max_length=200, null=True)),
                ('TopMenuImage', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, null=True)),
                ('Quantity', models.CharField(max_length=200, null=True)),
                ('Instock', models.CharField(max_length=200, null=True)),
                ('ProductTitle', models.CharField(max_length=500, null=True)),
                ('PriceIn', models.CharField(max_length=200, null=True)),
                ('PriceOut', models.CharField(max_length=200, null=True)),
                ('ProductImage', models.ImageField(upload_to='ProductImages/')),
                ('ProductDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProductDescription', ckeditor.fields.RichTextField(null=True)),
                ('CategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('SupplierID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='tblProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductDetailImageName', models.CharField(max_length=200, null=True)),
                ('ProductDetailImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('ImageDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblproducts')),
            ],
        ),
        migrations.CreateModel(
            name='tblProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductDetailName', models.CharField(max_length=200, null=True)),
                ('ProductDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProductSize', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('ProductColor', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblproducts')),
            ],
        ),
        migrations.CreateModel(
            name='tblSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideName', models.CharField(max_length=200, null=True)),
                ('SlideImage', models.ImageField(null=True, upload_to='images/')),
                ('SlideDescription', ckeditor.fields.RichTextField(null=True)),
                ('Active', models.CharField(max_length=200, null=True)),
                ('CategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.CreateModel(
            name='tblSubTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubTopMenuName', models.CharField(max_length=200, null=True)),
                ('SubTopMenuImage', models.CharField(max_length=200, null=True)),
                ('TopMenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu')),
            ],
        ),
    ]
