# Generated by Django 5.1.4 on 2025-01-25 08:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tblfreshorganic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BestSellerName', models.CharField(max_length=200, null=True)),
                ('Quantity', models.CharField(max_length=200, null=True)),
                ('Instock', models.CharField(max_length=200, null=True)),
                ('BestSellerTitle', models.CharField(max_length=500, null=True)),
                ('PriceIn', models.CharField(max_length=200, null=True)),
                ('PriceOut', models.CharField(max_length=200, null=True)),
                ('BestSellerImage', models.ImageField(upload_to='ProductImages/')),
                ('BestSellerDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('BestSellerDescription', ckeditor.fields.RichTextField(null=True)),
                ('CategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('SupplierID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
        ),
    ]
